name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '01 07 * * *' # Runs at 07:01 UTC every day.
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in blog.mikaeels.com posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: 'https://blog.mikaeels.com/rss.xml'
